// <auto-generated />
namespace Festispec.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AccountActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201912301434056_AccountActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
