// <auto-generated />
namespace Festispec.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class InspectionInstructions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InspectionInstructions));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141846014_InspectionInstructions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
