name: Build & Test

on: [pull_request]

jobs:
  UserInterface:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build UI project
        run: |
          cd src/UserInterface
          dotnet restore
          dotnet build
          
  UnitTests:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Unit Tests
        run: |
          dotnet restore
          dotnet test
