name: PR Build

on: [pull_request]

jobs:
  build:

    runs-on: [windows-latest]
    steps:
      - name: Build UI project
        run: |
          dir
          cd src/UserInterface
          dotnet restore
          dotnet build
